// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Element } from './Element';
import type { Extension } from './Extension';

export interface BackboneElement extends Element {
    modifierExtension?: Extension[];
}

