// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Element } from './Element';
import type { Reference } from './Reference';
import type { Resource } from './Resource';

export interface Binary extends Resource {
    contentType: string;
    _contentType?: Element;
    data?: string;
    _data?: Element;
    securityContext?: Reference<'Resource'>;
}

