// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from './Attachment';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Element } from './Element';
import type { Identifier } from './Identifier';
import type { Reference } from './Reference';

export interface BodyStructure extends DomainResource {
    active?: boolean;
    _active?: Element;
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    image?: Attachment[];
    location?: CodeableConcept;
    locationQualifier?: CodeableConcept[];
    morphology?: CodeableConcept;
    patient: Reference<'Patient'>;
}

