// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from './Annotation';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { ContactPoint } from './ContactPoint';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Reference } from './Reference';


export interface CareTeamParticipant extends BackboneElement {
    member?: Reference<'CareTeam' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    onBehalfOf?: Reference<'Organization'>;
    period?: Period;
    role?: CodeableConcept[];
}

export interface CareTeam extends DomainResource {
    category?: CodeableConcept[];
    encounter?: Reference<'Encounter'>;
    identifier?: Identifier[];
    managingOrganization?: Reference<'Organization'>[];
    name?: string;
    _name?: Element;
    note?: Annotation[];
    participant?: CareTeamParticipant[];
    period?: Period;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition'>[];
    status?: 'proposed' | 'active' | 'suspended' | 'inactive' | 'entered-in-error';
    _status?: Element;
    subject?: Reference<'Group' | 'Patient'>;
    telecom?: ContactPoint[];
}

