// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from './Annotation';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Money } from './Money';
import type { Period } from './Period';
import type { Quantity } from './Quantity';
import type { Reference } from './Reference';
import type { Timing } from './Timing';


export interface ChargeItemPerformer extends BackboneElement {
    actor: Reference<'CareTeam' | 'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    function?: CodeableConcept;
}

export interface ChargeItem extends DomainResource {
    account?: Reference<'Account'>[];
    bodysite?: CodeableConcept[];
    code: CodeableConcept;
    context?: Reference<'Encounter' | 'EpisodeOfCare'>;
    costCenter?: Reference<'Organization'>;
    definitionCanonical?: string[];
    _definitionCanonical?: Element;
    definitionUri?: string[];
    _definitionUri?: Element;
    enteredDate?: string;
    _enteredDate?: Element;
    enterer?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    factorOverride?: number;
    _factorOverride?: Element;
    identifier?: Identifier[];
    note?: Annotation[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    occurrenceTiming?: Timing;
    overrideReason?: string;
    _overrideReason?: Element;
    partOf?: Reference<'ChargeItem'>[];
    performer?: ChargeItemPerformer[];
    performingOrganization?: Reference<'Organization'>;
    priceOverride?: Money;
    productCodeableConcept?: CodeableConcept;
    productReference?: Reference<'Device' | 'Medication' | 'Substance'>;
    quantity?: Quantity;
    reason?: CodeableConcept[];
    requestingOrganization?: Reference<'Organization'>;
    service?: Reference<'DiagnosticReport' | 'ImagingStudy' | 'Immunization' | 'MedicationAdministration' | 'MedicationDispense' | 'Observation' | 'Procedure' | 'SupplyDelivery'>[];
    status: 'planned' | 'billable' | 'not-billable' | 'aborted' | 'billed' | 'entered-in-error' | 'unknown';
    _status?: Element;
    subject: Reference<'Group' | 'Patient'>;
    supportingInformation?: Reference<'Resource'>[];
}

