// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Coding } from './Coding';
import type { Element } from './Element';

export interface CodeableConcept extends Element {
    coding?: Coding[];
    text?: string;
    _text?: Element;
}

