// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Age } from './Age';
import type { Annotation } from './Annotation';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Range } from './Range';
import type { Reference } from './Reference';


export interface ConditionEvidence extends BackboneElement {
    code?: CodeableConcept[];
    detail?: Reference<'Resource'>[];
}

export interface ConditionStage extends BackboneElement {
    assessment?: Reference<'ClinicalImpression' | 'DiagnosticReport' | 'Observation'>[];
    summary?: CodeableConcept;
    type?: CodeableConcept;
}

export interface Condition extends DomainResource {
    abatementAge?: Age;
    abatementDateTime?: string;
    _abatementDateTime?: Element;
    abatementPeriod?: Period;
    abatementRange?: Range;
    abatementString?: string;
    _abatementString?: Element;
    asserter?: Reference<'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    bodySite?: CodeableConcept[];
    category?: CodeableConcept[];
    clinicalStatus?: CodeableConcept;
    code?: CodeableConcept;
    encounter?: Reference<'Encounter'>;
    evidence?: ConditionEvidence[];
    identifier?: Identifier[];
    note?: Annotation[];
    onsetAge?: Age;
    onsetDateTime?: string;
    _onsetDateTime?: Element;
    onsetPeriod?: Period;
    onsetRange?: Range;
    onsetString?: string;
    _onsetString?: Element;
    recordedDate?: string;
    _recordedDate?: Element;
    recorder?: Reference<'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    severity?: CodeableConcept;
    stage?: ConditionStage[];
    subject: Reference<'Group' | 'Patient'>;
    verificationStatus?: CodeableConcept;
}

