// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from './Extension';
import type { Narrative } from './Narrative';
import type { Resource } from './Resource';

export interface DomainResource extends Resource {
    contained?: Resource[];
    extension?: Extension[];
    modifierExtension?: Extension[];
    text?: Narrative;
}

