// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { Quantity } from './Quantity';
import type { Range } from './Range';
import type { Ratio } from './Ratio';
import type { Timing } from './Timing';


export interface DosageDoseAndRate extends BackboneElement {
    doseQuantity?: Quantity;
    doseRange?: Range;
    rateQuantity?: Quantity;
    rateRange?: Range;
    rateRatio?: Ratio;
    type?: CodeableConcept;
}

export interface Dosage extends BackboneElement {
    additionalInstruction?: CodeableConcept[];
    asNeededBoolean?: boolean;
    _asNeededBoolean?: Element;
    asNeededCodeableConcept?: CodeableConcept;
    doseAndRate?: DosageDoseAndRate[];
    maxDosePerAdministration?: Quantity;
    maxDosePerLifetime?: Quantity;
    maxDosePerPeriod?: Ratio;
    method?: CodeableConcept;
    patientInstruction?: string;
    _patientInstruction?: Element;
    route?: CodeableConcept;
    sequence?: number;
    _sequence?: Element;
    site?: CodeableConcept;
    text?: string;
    _text?: Element;
    timing?: Timing;
}

