// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from './CodeableConcept';
import type { Coding } from './Coding';
import type { ContactPoint } from './ContactPoint';
import type { DomainResource } from './DomainResource';
import type { Element } from './Element';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Reference } from './Reference';

export interface Endpoint extends DomainResource {
    address: string;
    _address?: Element;
    connectionType: Coding;
    contact?: ContactPoint[];
    header?: string[];
    _header?: Element;
    identifier?: Identifier[];
    managingOrganization?: Reference<'Organization'>;
    name?: string;
    _name?: Element;
    payloadMimeType?: string[];
    _payloadMimeType?: Element;
    payloadType: CodeableConcept[];
    period?: Period;
    status: 'active' | 'suspended' | 'error' | 'off' | 'entered-in-error' | 'test';
    _status?: Element;
}

