// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { DomainResource } from './DomainResource';
import type { Element } from './Element';
import type { Identifier } from './Identifier';
import type { Reference } from './Reference';

export interface EnrollmentRequest extends DomainResource {
    candidate?: Reference<'Patient'>;
    coverage?: Reference<'Coverage'>;
    created?: string;
    _created?: Element;
    identifier?: Identifier[];
    insurer?: Reference<'Organization'>;
    provider?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    status?: 'active' | 'cancelled' | 'draft' | 'entered-in-error';
    _status?: Element;
}

