// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Reference } from './Reference';


export interface EpisodeOfCareDiagnosis extends BackboneElement {
    condition: Reference<'Condition'>;
    rank?: number;
    role?: CodeableConcept;
}

export interface EpisodeOfCareStatusHistory extends BackboneElement {
    period: Period;
    status: 'planned' | 'waitlist' | 'active' | 'onhold' | 'finished' | 'cancelled' | 'entered-in-error';
}

export interface EpisodeOfCare extends DomainResource {
    account?: Reference<'Account'>[];
    careManager?: Reference<'Practitioner' | 'PractitionerRole'>;
    diagnosis?: EpisodeOfCareDiagnosis[];
    identifier?: Identifier[];
    managingOrganization?: Reference<'Organization'>;
    patient: Reference<'Patient'>;
    period?: Period;
    referralRequest?: Reference<'ServiceRequest'>[];
    status: 'planned' | 'waitlist' | 'active' | 'onhold' | 'finished' | 'cancelled' | 'entered-in-error';
    _status?: Element;
    statusHistory?: EpisodeOfCareStatusHistory[];
    team?: Reference<'CareTeam'>[];
    type?: CodeableConcept[];
}

