// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from './Annotation';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { ContactDetail } from './ContactDetail';
import type { DataRequirement } from './DataRequirement';
import type { DomainResource } from './DomainResource';
import type { Duration } from './Duration';
import type { Expression } from './Expression';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Reference } from './Reference';
import type { RelatedArtifact } from './RelatedArtifact';
import type { Timing } from './Timing';
import type { TriggerDefinition } from './TriggerDefinition';
import type { UsageContext } from './UsageContext';


export interface EvidenceVariableCharacteristic extends BackboneElement {
    definitionCanonical?: string;
    definitionCodeableConcept?: CodeableConcept;
    definitionDataRequirement?: DataRequirement;
    definitionExpression?: Expression;
    definitionReference?: Reference<'Group'>;
    definitionTriggerDefinition?: TriggerDefinition;
    description?: string;
    exclude?: boolean;
    groupMeasure?: 'mean' | 'median' | 'mean-of-mean' | 'mean-of-median' | 'median-of-mean' | 'median-of-median';
    participantEffectiveDateTime?: string;
    participantEffectiveDuration?: Duration;
    participantEffectivePeriod?: Period;
    participantEffectiveTiming?: Timing;
    timeFromStart?: Duration;
    usageContext?: UsageContext[];
}

export interface EvidenceVariable extends DomainResource {
    approvalDate?: string;
    _approvalDate?: Element;
    author?: ContactDetail[];
    characteristic: EvidenceVariableCharacteristic[];
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    name?: string;
    _name?: Element;
    note?: Annotation[];
    publisher?: string;
    _publisher?: Element;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    shortTitle?: string;
    _shortTitle?: Element;
    status: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    subtitle?: string;
    _subtitle?: Element;
    title?: string;
    _title?: Element;
    topic?: CodeableConcept[];
    type?: 'dichotomous' | 'continuous' | 'descriptive';
    _type?: Element;
    url?: string;
    _url?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}

