// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Age } from './Age';
import type { Annotation } from './Annotation';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Range } from './Range';
import type { Reference } from './Reference';


export interface FamilyMemberHistoryCondition extends BackboneElement {
    code: CodeableConcept;
    contributedToDeath?: boolean;
    note?: Annotation[];
    onsetAge?: Age;
    onsetPeriod?: Period;
    onsetRange?: Range;
    onsetString?: string;
    outcome?: CodeableConcept;
}

export interface FamilyMemberHistory extends DomainResource {
    ageAge?: Age;
    ageRange?: Range;
    ageString?: string;
    _ageString?: Element;
    bornDate?: string;
    _bornDate?: Element;
    bornPeriod?: Period;
    bornString?: string;
    _bornString?: Element;
    condition?: FamilyMemberHistoryCondition[];
    dataAbsentReason?: CodeableConcept;
    date?: string;
    _date?: Element;
    deceasedAge?: Age;
    deceasedBoolean?: boolean;
    _deceasedBoolean?: Element;
    deceasedDate?: string;
    _deceasedDate?: Element;
    deceasedRange?: Range;
    deceasedString?: string;
    _deceasedString?: Element;
    estimatedAge?: boolean;
    _estimatedAge?: Element;
    identifier?: Identifier[];
    instantiatesCanonical?: string[];
    _instantiatesCanonical?: Element;
    instantiatesUri?: string[];
    _instantiatesUri?: Element;
    name?: string;
    _name?: Element;
    note?: Annotation[];
    patient: Reference<'Patient'>;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'AllergyIntolerance' | 'Condition' | 'DiagnosticReport' | 'DocumentReference' | 'Observation' | 'QuestionnaireResponse'>[];
    relationship: CodeableConcept;
    sex?: CodeableConcept;
    status: 'partial' | 'completed' | 'entered-in-error' | 'health-unknown';
    _status?: Element;
}

