// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Element } from './Element';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Reference } from './Reference';

export interface Flag extends DomainResource {
    author?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole'>;
    category?: CodeableConcept[];
    code: CodeableConcept;
    encounter?: Reference<'Encounter'>;
    identifier?: Identifier[];
    period?: Period;
    status: 'active' | 'inactive' | 'entered-in-error';
    _status?: Element;
    subject: Reference<'Group' | 'Location' | 'Medication' | 'Organization' | 'Patient' | 'PlanDefinition' | 'Practitioner' | 'Procedure'>;
}

