// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from './Annotation';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Duration } from './Duration';
import type { Identifier } from './Identifier';
import type { Quantity } from './Quantity';
import type { Range } from './Range';
import type { Ratio } from './Ratio';
import type { Reference } from './Reference';


export interface GoalTarget extends BackboneElement {
    detailBoolean?: boolean;
    detailCodeableConcept?: CodeableConcept;
    detailInteger?: number;
    detailQuantity?: Quantity;
    detailRange?: Range;
    detailRatio?: Ratio;
    detailString?: string;
    dueDate?: string;
    dueDuration?: Duration;
    measure?: CodeableConcept;
}

export interface Goal extends DomainResource {
    achievementStatus?: CodeableConcept;
    addresses?: Reference<'Condition' | 'MedicationStatement' | 'NutritionOrder' | 'Observation' | 'RiskAssessment' | 'ServiceRequest'>[];
    category?: CodeableConcept[];
    description: CodeableConcept;
    expressedBy?: Reference<'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    identifier?: Identifier[];
    lifecycleStatus: 'proposed' | 'planned' | 'accepted' | 'cancelled' | 'entered-in-error' | 'rejected' | 'active' | 'on-hold' | 'completed';
    _lifecycleStatus?: Element;
    note?: Annotation[];
    outcomeCode?: CodeableConcept[];
    outcomeReference?: Reference<'Observation'>[];
    priority?: CodeableConcept;
    startCodeableConcept?: CodeableConcept;
    startDate?: string;
    _startDate?: Element;
    statusDate?: string;
    _statusDate?: Element;
    statusReason?: string;
    _statusReason?: Element;
    subject: Reference<'Group' | 'Organization' | 'Patient'>;
    target?: GoalTarget[];
}

