// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Quantity } from './Quantity';
import type { Range } from './Range';
import type { Reference } from './Reference';


export interface GroupCharacteristic extends BackboneElement {
    code: CodeableConcept;
    exclude: boolean;
    period?: Period;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueRange?: Range;
    valueReference?: Reference;
}

export interface GroupMember extends BackboneElement {
    entity: Reference<'Device' | 'Group' | 'Medication' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'Substance'>;
    inactive?: boolean;
    period?: Period;
}

export interface Group extends DomainResource {
    active?: boolean;
    _active?: Element;
    actual: boolean;
    _actual?: Element;
    characteristic?: GroupCharacteristic[];
    code?: CodeableConcept;
    identifier?: Identifier[];
    managingEntity?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    member?: GroupMember[];
    name?: string;
    _name?: Element;
    quantity?: number;
    _quantity?: Element;
    type: 'person' | 'animal' | 'practitioner' | 'device' | 'medication' | 'substance';
    _type?: Element;
}

