// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Element } from './Element';
import type { Identifier } from './Identifier';
import type { Reference } from './Reference';

export interface ImmunizationEvaluation extends DomainResource {
    authority?: Reference<'Organization'>;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    doseNumberPositiveInt?: number;
    _doseNumberPositiveInt?: Element;
    doseNumberString?: string;
    _doseNumberString?: Element;
    doseStatus: CodeableConcept;
    doseStatusReason?: CodeableConcept[];
    identifier?: Identifier[];
    immunizationEvent: Reference<'Immunization'>;
    patient: Reference<'Patient'>;
    series?: string;
    _series?: Element;
    seriesDosesPositiveInt?: number;
    _seriesDosesPositiveInt?: Element;
    seriesDosesString?: string;
    _seriesDosesString?: Element;
    status: 'completed' | 'entered-in-error';
    _status?: Element;
    targetDisease: CodeableConcept;
}

