// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from './Annotation';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Dosage } from './Dosage';
import type { Element } from './Element';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Reference } from './Reference';

export interface MedicationStatement extends DomainResource {
    basedOn?: Reference<'CarePlan' | 'MedicationRequest' | 'ServiceRequest'>[];
    category?: CodeableConcept;
    context?: Reference<'Encounter' | 'EpisodeOfCare'>;
    dateAsserted?: string;
    _dateAsserted?: Element;
    derivedFrom?: Reference<'Resource'>[];
    dosage?: Dosage[];
    effectiveDateTime?: string;
    _effectiveDateTime?: Element;
    effectivePeriod?: Period;
    identifier?: Identifier[];
    informationSource?: Reference<'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    medicationCodeableConcept?: CodeableConcept;
    medicationReference?: Reference<'Medication'>;
    note?: Annotation[];
    partOf?: Reference<'MedicationAdministration' | 'MedicationDispense' | 'MedicationStatement' | 'Observation' | 'Procedure'>[];
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition' | 'DiagnosticReport' | 'Observation'>[];
    status: 'active' | 'completed' | 'entered-in-error' | 'intended' | 'stopped' | 'on-hold' | 'unknown' | 'not-taken';
    _status?: Element;
    statusReason?: CodeableConcept[];
    subject: Reference<'Group' | 'Patient'>;
}

