// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { ProdCharacteristic } from './ProdCharacteristic';
import type { Quantity } from './Quantity';
import type { Reference } from './Reference';

export interface MedicinalProductManufactured extends DomainResource {
    ingredient?: Reference<'MedicinalProductIngredient'>[];
    manufacturedDoseForm: CodeableConcept;
    manufacturer?: Reference<'Organization'>[];
    otherCharacteristics?: CodeableConcept[];
    physicalCharacteristics?: ProdCharacteristic;
    quantity: Quantity;
    unitOfPresentation?: CodeableConcept;
}

