// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Duration } from './Duration';
import type { Identifier } from './Identifier';
import type { Quantity } from './Quantity';
import type { Ratio } from './Ratio';
import type { Reference } from './Reference';


export interface MedicinalProductPharmaceuticalCharacteristics extends BackboneElement {
    code: CodeableConcept;
    status?: CodeableConcept;
}

export interface MedicinalProductPharmaceuticalRouteOfAdministration extends BackboneElement {
    code: CodeableConcept;
    firstDose?: Quantity;
    maxDosePerDay?: Quantity;
    maxDosePerTreatmentPeriod?: Ratio;
    maxSingleDose?: Quantity;
    maxTreatmentPeriod?: Duration;
    targetSpecies?: MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies[];
}

export interface MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies extends BackboneElement {
    code: CodeableConcept;
    withdrawalPeriod?: MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod[];
}

export interface MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod extends BackboneElement {
    supportingInformation?: string;
    tissue: CodeableConcept;
    value: Quantity;
}

export interface MedicinalProductPharmaceutical extends DomainResource {
    administrableDoseForm: CodeableConcept;
    characteristics?: MedicinalProductPharmaceuticalCharacteristics[];
    device?: Reference<'DeviceDefinition'>[];
    identifier?: Identifier[];
    ingredient?: Reference<'MedicinalProductIngredient'>[];
    routeOfAdministration: MedicinalProductPharmaceuticalRouteOfAdministration[];
    unitOfPresentation?: CodeableConcept;
}

