// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Reference } from './Reference';


export interface MedicinalProductInteractionInteractant extends BackboneElement {
    itemCodeableConcept?: CodeableConcept;
    itemReference?: Reference<'Medication' | 'MedicinalProduct' | 'ObservationDefinition' | 'Substance'>;
}

export interface MedicinalProductInteraction extends DomainResource {
    description?: string;
    _description?: Element;
    effect?: CodeableConcept;
    incidence?: CodeableConcept;
    interactant?: MedicinalProductInteractionInteractant[];
    management?: CodeableConcept;
    subject?: Reference<'Medication' | 'MedicinalProduct' | 'Substance'>[];
    type?: CodeableConcept;
}

