// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Ratio } from './Ratio';
import type { Reference } from './Reference';


export interface MedicationBatch extends BackboneElement {
    expirationDate?: string;
    lotNumber?: string;
}

export interface MedicationIngredient extends BackboneElement {
    isActive?: boolean;
    itemCodeableConcept?: CodeableConcept;
    itemReference?: Reference<'Medication' | 'Substance'>;
    strength?: Ratio;
}

export interface Medication extends DomainResource {
    amount?: Ratio;
    batch?: MedicationBatch;
    code?: CodeableConcept;
    form?: CodeableConcept;
    identifier?: Identifier[];
    ingredient?: MedicationIngredient[];
    manufacturer?: Reference<'Organization'>;
    status?: 'active' | 'inactive' | 'entered-in-error';
    _status?: Element;
}

