// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from './Annotation';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Dosage } from './Dosage';
import type { Identifier } from './Identifier';
import type { Quantity } from './Quantity';
import type { Reference } from './Reference';


export interface MedicationDispensePerformer extends BackboneElement {
    actor: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    function?: CodeableConcept;
}

export interface MedicationDispenseSubstitution extends BackboneElement {
    reason?: CodeableConcept[];
    responsibleParty?: Reference<'Practitioner' | 'PractitionerRole'>[];
    type?: CodeableConcept;
    wasSubstituted: boolean;
}

export interface MedicationDispense extends DomainResource {
    authorizingPrescription?: Reference<'MedicationRequest'>[];
    category?: CodeableConcept;
    context?: Reference<'Encounter' | 'EpisodeOfCare'>;
    daysSupply?: Quantity;
    destination?: Reference<'Location'>;
    detectedIssue?: Reference<'DetectedIssue'>[];
    dosageInstruction?: Dosage[];
    eventHistory?: Reference<'Provenance'>[];
    identifier?: Identifier[];
    location?: Reference<'Location'>;
    medicationCodeableConcept?: CodeableConcept;
    medicationReference?: Reference<'Medication'>;
    note?: Annotation[];
    partOf?: Reference<'Procedure'>[];
    performer?: MedicationDispensePerformer[];
    quantity?: Quantity;
    receiver?: Reference<'Patient' | 'Practitioner'>[];
    status: 'preparation' | 'in-progress' | 'cancelled' | 'on-hold' | 'completed' | 'entered-in-error' | 'stopped' | 'declined' | 'unknown';
    _status?: Element;
    statusReasonCodeableConcept?: CodeableConcept;
    statusReasonReference?: Reference<'DetectedIssue'>;
    subject?: Reference<'Group' | 'Patient'>;
    substitution?: MedicationDispenseSubstitution;
    supportingInformation?: Reference<'Resource'>[];
    type?: CodeableConcept;
    whenHandedOver?: string;
    _whenHandedOver?: Element;
    whenPrepared?: string;
    _whenPrepared?: Element;
}

