// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Population } from './Population';
import type { Reference } from './Reference';


export interface MedicinalProductContraindicationOtherTherapy extends BackboneElement {
    medicationCodeableConcept?: CodeableConcept;
    medicationReference?: Reference<'Medication' | 'MedicinalProduct' | 'Substance' | 'SubstanceSpecification'>;
    therapyRelationshipType: CodeableConcept;
}

export interface MedicinalProductContraindication extends DomainResource {
    comorbidity?: CodeableConcept[];
    disease?: CodeableConcept;
    diseaseStatus?: CodeableConcept;
    otherTherapy?: MedicinalProductContraindicationOtherTherapy[];
    population?: Population[];
    subject?: Reference<'Medication' | 'MedicinalProduct'>[];
    therapeuticIndication?: Reference<'MedicinalProductIndication'>[];
}

