// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { MarketingStatus } from './MarketingStatus';
import type { ProdCharacteristic } from './ProdCharacteristic';
import type { ProductShelfLife } from './ProductShelfLife';
import type { Quantity } from './Quantity';
import type { Reference } from './Reference';


export interface MedicinalProductPackagedBatchIdentifier extends BackboneElement {
    immediatePackaging?: Identifier;
    outerPackaging: Identifier;
}

export interface MedicinalProductPackagedPackageItem extends BackboneElement {
    alternateMaterial?: CodeableConcept[];
    device?: Reference<'DeviceDefinition'>[];
    identifier?: Identifier[];
    manufacturedItem?: Reference<'MedicinalProductManufactured'>[];
    manufacturer?: Reference<'Organization'>[];
    material?: CodeableConcept[];
    otherCharacteristics?: CodeableConcept[];
    packageItem?: MedicinalProductPackagedPackageItem[];
    physicalCharacteristics?: ProdCharacteristic;
    quantity: Quantity;
    shelfLifeStorage?: ProductShelfLife[];
    type: CodeableConcept;
}

export interface MedicinalProductPackaged extends DomainResource {
    batchIdentifier?: MedicinalProductPackagedBatchIdentifier[];
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    legalStatusOfSupply?: CodeableConcept;
    manufacturer?: Reference<'Organization'>[];
    marketingAuthorization?: Reference<'MedicinalProductAuthorization'>;
    marketingStatus?: MarketingStatus[];
    packageItem: MedicinalProductPackagedPackageItem[];
    subject?: Reference<'MedicinalProduct'>[];
}

