// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Population } from './Population';
import type { Reference } from './Reference';

export interface MedicinalProductUndesirableEffect extends DomainResource {
    classification?: CodeableConcept;
    frequencyOfOccurrence?: CodeableConcept;
    population?: Population[];
    subject?: Reference<'Medication' | 'MedicinalProduct'>[];
    symptomConditionEffect?: CodeableConcept;
}

