// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Range } from './Range';
import type { Reference } from './Reference';


export interface ObservationDefinitionQualifiedInterval extends BackboneElement {
    age?: Range;
    appliesTo?: CodeableConcept[];
    category?: 'reference' | 'critical' | 'absolute';
    condition?: string;
    context?: CodeableConcept;
    gender?: 'male' | 'female' | 'other' | 'unknown';
    gestationalAge?: Range;
    range?: Range;
}

export interface ObservationDefinitionQuantitativeDetails extends BackboneElement {
    conversionFactor?: number;
    customaryUnit?: CodeableConcept;
    decimalPrecision?: number;
    unit?: CodeableConcept;
}

export interface ObservationDefinition extends DomainResource {
    abnormalCodedValueSet?: Reference<'ValueSet'>;
    category?: CodeableConcept[];
    code: CodeableConcept;
    criticalCodedValueSet?: Reference<'ValueSet'>;
    identifier?: Identifier[];
    method?: CodeableConcept;
    multipleResultsAllowed?: boolean;
    _multipleResultsAllowed?: Element;
    normalCodedValueSet?: Reference<'ValueSet'>;
    permittedDataType?: 'Quantity' | 'CodeableConcept' | 'string' | 'boolean' | 'integer' | 'Range' | 'Ratio' | 'SampledData' | 'time' | 'dateTime' | 'Period'[];
    _permittedDataType?: Element;
    preferredReportName?: string;
    _preferredReportName?: Element;
    qualifiedInterval?: ObservationDefinitionQualifiedInterval[];
    quantitativeDetails?: ObservationDefinitionQuantitativeDetails;
    validCodedValueSet?: Reference<'ValueSet'>;
}

