// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Address } from './Address';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { ContactPoint } from './ContactPoint';
import type { DomainResource } from './DomainResource';
import type { HumanName } from './HumanName';
import type { Identifier } from './Identifier';
import type { Reference } from './Reference';


export interface OrganizationContact extends BackboneElement {
    address?: Address;
    name?: HumanName;
    purpose?: CodeableConcept;
    telecom?: ContactPoint[];
}

export interface Organization extends DomainResource {
    active?: boolean;
    _active?: Element;
    address?: Address[];
    alias?: string[];
    _alias?: Element;
    contact?: OrganizationContact[];
    endpoint?: Reference<'Endpoint'>[];
    identifier?: Identifier[];
    name?: string;
    _name?: Element;
    partOf?: Reference<'Organization'>;
    telecom?: ContactPoint[];
    type?: CodeableConcept[];
}

