// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Money } from './Money';
import type { Period } from './Period';
import type { Reference } from './Reference';


export interface PaymentReconciliationDetail extends BackboneElement {
    amount?: Money;
    date?: string;
    identifier?: Identifier;
    payee?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    predecessor?: Identifier;
    request?: Reference<'Resource'>;
    response?: Reference<'Resource'>;
    responsible?: Reference<'PractitionerRole'>;
    submitter?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    type: CodeableConcept;
}

export interface PaymentReconciliationProcessNote extends BackboneElement {
    text?: string;
    type?: 'display' | 'print' | 'printoper';
}

export interface PaymentReconciliation extends DomainResource {
    created: string;
    _created?: Element;
    detail?: PaymentReconciliationDetail[];
    disposition?: string;
    _disposition?: Element;
    formCode?: CodeableConcept;
    identifier?: Identifier[];
    outcome?: 'queued' | 'complete' | 'error' | 'partial';
    _outcome?: Element;
    paymentAmount: Money;
    paymentDate: string;
    _paymentDate?: Element;
    paymentIdentifier?: Identifier;
    paymentIssuer?: Reference<'Organization'>;
    period?: Period;
    processNote?: PaymentReconciliationProcessNote[];
    request?: Reference<'Task'>;
    requestor?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    status: 'active' | 'cancelled' | 'draft' | 'entered-in-error';
    _status?: Element;
}

