// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Element } from './Element';
import type { Identifier } from './Identifier';
import type { Money } from './Money';
import type { Reference } from './Reference';

export interface PaymentNotice extends DomainResource {
    amount: Money;
    created: string;
    _created?: Element;
    identifier?: Identifier[];
    payee?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    payment: Reference<'PaymentReconciliation'>;
    paymentDate?: string;
    _paymentDate?: Element;
    paymentStatus?: CodeableConcept;
    provider?: Reference<'Organization' | 'Practitioner' | 'PractitionerRole'>;
    recipient: Reference<'Organization'>;
    request?: Reference<'Resource'>;
    response?: Reference<'Resource'>;
    status: 'active' | 'cancelled' | 'draft' | 'entered-in-error';
    _status?: Element;
}

