// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Element } from './Element';

export interface Period extends Element {
    end?: string;
    _end?: Element;
    start?: string;
    _start?: Element;
}

