// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Address } from './Address';
import type { Attachment } from './Attachment';
import type { BackboneElement } from './BackboneElement';
import type { ContactPoint } from './ContactPoint';
import type { DomainResource } from './DomainResource';
import type { HumanName } from './HumanName';
import type { Identifier } from './Identifier';
import type { Reference } from './Reference';


export interface PersonLink extends BackboneElement {
    assurance?: 'level1' | 'level2' | 'level3' | 'level4';
    target: Reference<'Patient' | 'Person' | 'Practitioner' | 'RelatedPerson'>;
}

export interface Person extends DomainResource {
    active?: boolean;
    _active?: Element;
    address?: Address[];
    birthDate?: string;
    _birthDate?: Element;
    gender?: 'male' | 'female' | 'other' | 'unknown';
    _gender?: Element;
    identifier?: Identifier[];
    link?: PersonLink[];
    managingOrganization?: Reference<'Organization'>;
    name?: HumanName[];
    photo?: Attachment;
    telecom?: ContactPoint[];
}

