// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { Range } from './Range';

export interface Population extends BackboneElement {
    ageCodeableConcept?: CodeableConcept;
    ageRange?: Range;
    gender?: CodeableConcept;
    physiologicalCondition?: CodeableConcept;
    race?: CodeableConcept;
}

