// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { ContactPoint } from './ContactPoint';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Reference } from './Reference';


export interface PractitionerRoleAvailableTime extends BackboneElement {
    allDay?: boolean;
    availableEndTime?: string;
    availableStartTime?: string;
    daysOfWeek?: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun'[];
}

export interface PractitionerRoleNotAvailable extends BackboneElement {
    description: string;
    during?: Period;
}

export interface PractitionerRole extends DomainResource {
    active?: boolean;
    _active?: Element;
    availabilityExceptions?: string;
    _availabilityExceptions?: Element;
    availableTime?: PractitionerRoleAvailableTime[];
    code?: CodeableConcept[];
    endpoint?: Reference<'Endpoint'>[];
    healthcareService?: Reference<'HealthcareService'>[];
    identifier?: Identifier[];
    location?: Reference<'Location'>[];
    notAvailable?: PractitionerRoleNotAvailable[];
    organization?: Reference<'Organization'>;
    period?: Period;
    practitioner?: Reference<'Practitioner'>;
    specialty?: CodeableConcept[];
    telecom?: ContactPoint[];
}

