// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Address } from './Address';
import type { Attachment } from './Attachment';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { ContactPoint } from './ContactPoint';
import type { DomainResource } from './DomainResource';
import type { HumanName } from './HumanName';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Reference } from './Reference';


export interface PractitionerQualification extends BackboneElement {
    code: CodeableConcept;
    identifier?: Identifier[];
    issuer?: Reference<'Organization'>;
    period?: Period;
}

export interface Practitioner extends DomainResource {
    active?: boolean;
    _active?: Element;
    address?: Address[];
    birthDate?: string;
    _birthDate?: Element;
    communication?: CodeableConcept[];
    gender?: 'male' | 'female' | 'other' | 'unknown';
    _gender?: Element;
    identifier?: Identifier[];
    name?: HumanName[];
    photo?: Attachment[];
    qualification?: PractitionerQualification[];
    telecom?: ContactPoint[];
}

