// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from './Attachment';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { Quantity } from './Quantity';

export interface ProdCharacteristic extends BackboneElement {
    color?: string[];
    _color?: Element;
    depth?: Quantity;
    externalDiameter?: Quantity;
    height?: Quantity;
    image?: Attachment[];
    imprint?: string[];
    _imprint?: Element;
    nominalVolume?: Quantity;
    scoring?: CodeableConcept;
    shape?: string;
    _shape?: Element;
    weight?: Quantity;
    width?: Quantity;
}

