// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { Identifier } from './Identifier';
import type { Quantity } from './Quantity';

export interface ProductShelfLife extends BackboneElement {
    identifier?: Identifier;
    period: Quantity;
    specialPrecautionsForStorage?: CodeableConcept[];
    type: CodeableConcept;
}

