// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Period } from './Period';
import type { Reference } from './Reference';
import type { Signature } from './Signature';


export interface ProvenanceAgent extends BackboneElement {
    onBehalfOf?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    role?: CodeableConcept[];
    type?: CodeableConcept;
    who: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
}

export interface ProvenanceEntity extends BackboneElement {
    agent?: ProvenanceAgent[];
    role: 'derivation' | 'revision' | 'quotation' | 'source' | 'removal';
    what: Reference<'Resource'>;
}

export interface Provenance extends DomainResource {
    activity?: CodeableConcept;
    agent: ProvenanceAgent[];
    entity?: ProvenanceEntity[];
    location?: Reference<'Location'>;
    occurredDateTime?: string;
    _occurredDateTime?: Element;
    occurredPeriod?: Period;
    policy?: string[];
    _policy?: Element;
    reason?: CodeableConcept[];
    recorded: string;
    _recorded?: Element;
    signature?: Signature[];
    target: Reference<'Resource'>[];
}

