// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Element } from './Element';
import type { Identifier } from './Identifier';

export interface Reference<T extends string = string> extends Element {
    display?: string;
    _display?: Element;
    identifier?: Identifier;
    reference?: `${T}/${string}`;
    _reference?: Element;
    type?: string;
    _type?: Element;
}

