// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { DomainResource } from './DomainResource';
import type { Element } from './Element';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Reference } from './Reference';

export interface ResearchSubject extends DomainResource {
    actualArm?: string;
    _actualArm?: Element;
    assignedArm?: string;
    _assignedArm?: Element;
    consent?: Reference<'Consent'>;
    identifier?: Identifier[];
    individual: Reference<'Patient'>;
    period?: Period;
    status: 'candidate' | 'eligible' | 'follow-up' | 'ineligible' | 'not-registered' | 'off-study' | 'on-study' | 'on-study-intervention' | 'on-study-observation' | 'pending-on-study' | 'potential-candidate' | 'screening' | 'withdrawn';
    _status?: Element;
    study: Reference<'ResearchStudy'>;
}

