// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from './Annotation';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { ContactDetail } from './ContactDetail';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Reference } from './Reference';
import type { RelatedArtifact } from './RelatedArtifact';


export interface ResearchStudyArm extends BackboneElement {
    description?: string;
    name: string;
    type?: CodeableConcept;
}

export interface ResearchStudyObjective extends BackboneElement {
    name?: string;
    type?: CodeableConcept;
}

export interface ResearchStudy extends DomainResource {
    arm?: ResearchStudyArm[];
    category?: CodeableConcept[];
    condition?: CodeableConcept[];
    contact?: ContactDetail[];
    description?: string;
    _description?: Element;
    enrollment?: Reference<'Group'>[];
    focus?: CodeableConcept[];
    identifier?: Identifier[];
    keyword?: CodeableConcept[];
    location?: CodeableConcept[];
    note?: Annotation[];
    objective?: ResearchStudyObjective[];
    partOf?: Reference<'ResearchStudy'>[];
    period?: Period;
    phase?: CodeableConcept;
    primaryPurposeType?: CodeableConcept;
    principalInvestigator?: Reference<'Practitioner' | 'PractitionerRole'>;
    protocol?: Reference<'PlanDefinition'>[];
    reasonStopped?: CodeableConcept;
    relatedArtifact?: RelatedArtifact[];
    site?: Reference<'Location'>[];
    sponsor?: Reference<'Organization'>;
    status: 'active' | 'administratively-completed' | 'approved' | 'closed-to-accrual' | 'closed-to-accrual-and-intervention' | 'completed' | 'disapproved' | 'in-review' | 'temporarily-closed-to-accrual' | 'temporarily-closed-to-accrual-and-intervention' | 'withdrawn';
    _status?: Element;
    title?: string;
    _title?: Element;
}

