// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Coding } from './Coding';
import type { Element } from './Element';
import type { Reference } from './Reference';

export interface Signature extends Element {
    data?: string;
    _data?: Element;
    onBehalfOf?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    sigFormat?: string;
    _sigFormat?: Element;
    targetFormat?: string;
    _targetFormat?: Element;
    type: Coding[];
    when: string;
    _when?: Element;
    who: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
}

