// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Duration } from './Duration';
import type { Identifier } from './Identifier';
import type { Quantity } from './Quantity';
import type { Range } from './Range';
import type { Reference } from './Reference';


export interface SpecimenDefinitionTypeTested extends BackboneElement {
    container?: SpecimenDefinitionTypeTestedContainer;
    handling?: SpecimenDefinitionTypeTestedHandling[];
    isDerived?: boolean;
    preference: 'preferred' | 'alternate';
    rejectionCriterion?: CodeableConcept[];
    requirement?: string;
    retentionTime?: Duration;
    type?: CodeableConcept;
}

export interface SpecimenDefinitionTypeTestedContainer extends BackboneElement {
    additive?: SpecimenDefinitionTypeTestedContainerAdditive[];
    cap?: CodeableConcept;
    capacity?: Quantity;
    description?: string;
    material?: CodeableConcept;
    minimumVolumeQuantity?: Quantity;
    minimumVolumeString?: string;
    preparation?: string;
    type?: CodeableConcept;
}

export interface SpecimenDefinitionTypeTestedContainerAdditive extends BackboneElement {
    additiveCodeableConcept?: CodeableConcept;
    additiveReference?: Reference<'Substance'>;
}

export interface SpecimenDefinitionTypeTestedHandling extends BackboneElement {
    instruction?: string;
    maxDuration?: Duration;
    temperatureQualifier?: CodeableConcept;
    temperatureRange?: Range;
}

export interface SpecimenDefinition extends DomainResource {
    collection?: CodeableConcept[];
    identifier?: Identifier;
    patientPreparation?: CodeableConcept[];
    timeAspect?: string;
    _timeAspect?: Element;
    typeCollected?: CodeableConcept;
    typeTested?: SpecimenDefinitionTypeTested[];
}

