// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Address } from './Address';
import type { Age } from './Age';
import type { Annotation } from './Annotation';
import type { Attachment } from './Attachment';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { Coding } from './Coding';
import type { ContactDetail } from './ContactDetail';
import type { ContactPoint } from './ContactPoint';
import type { Contributor } from './Contributor';
import type { Count } from './Count';
import type { DataRequirement } from './DataRequirement';
import type { Distance } from './Distance';
import type { DomainResource } from './DomainResource';
import type { Dosage } from './Dosage';
import type { Duration } from './Duration';
import type { Expression } from './Expression';
import type { HumanName } from './HumanName';
import type { Identifier } from './Identifier';
import type { Meta } from './Meta';
import type { Money } from './Money';
import type { ParameterDefinition } from './ParameterDefinition';
import type { Period } from './Period';
import type { Quantity } from './Quantity';
import type { Range } from './Range';
import type { Ratio } from './Ratio';
import type { Reference } from './Reference';
import type { RelatedArtifact } from './RelatedArtifact';
import type { SampledData } from './SampledData';
import type { Signature } from './Signature';
import type { Timing } from './Timing';
import type { TriggerDefinition } from './TriggerDefinition';
import type { UsageContext } from './UsageContext';


export interface StructureMapGroup extends BackboneElement {
    documentation?: string;
    extends?: string;
    input: StructureMapGroupInput[];
    name: string;
    rule: StructureMapGroupRule[];
    typeMode: 'none' | 'types' | 'type-and-types';
}

export interface StructureMapGroupInput extends BackboneElement {
    documentation?: string;
    mode: 'source' | 'target';
    name: string;
    type?: string;
}

export interface StructureMapGroupRule extends BackboneElement {
    dependent?: StructureMapGroupRuleDependent[];
    documentation?: string;
    name: string;
    rule?: StructureMapGroupRule[];
    source: StructureMapGroupRuleSource[];
    target?: StructureMapGroupRuleTarget[];
}

export interface StructureMapGroupRuleDependent extends BackboneElement {
    name: string;
    variable: string[];
}

export interface StructureMapGroupRuleSource extends BackboneElement {
    check?: string;
    condition?: string;
    context: string;
    defaultValueAddress?: Address;
    defaultValueAge?: Age;
    defaultValueAnnotation?: Annotation;
    defaultValueAttachment?: Attachment;
    defaultValueBase64Binary?: string;
    defaultValueBoolean?: boolean;
    defaultValueCanonical?: string;
    defaultValueCode?: string;
    defaultValueCodeableConcept?: CodeableConcept;
    defaultValueCoding?: Coding;
    defaultValueContactDetail?: ContactDetail;
    defaultValueContactPoint?: ContactPoint;
    defaultValueContributor?: Contributor;
    defaultValueCount?: Count;
    defaultValueDataRequirement?: DataRequirement;
    defaultValueDate?: string;
    defaultValueDateTime?: string;
    defaultValueDecimal?: number;
    defaultValueDistance?: Distance;
    defaultValueDosage?: Dosage;
    defaultValueDuration?: Duration;
    defaultValueExpression?: Expression;
    defaultValueHumanName?: HumanName;
    defaultValueId?: string;
    defaultValueIdentifier?: Identifier;
    defaultValueInstant?: string;
    defaultValueInteger?: number;
    defaultValueMarkdown?: string;
    defaultValueMeta?: Meta;
    defaultValueMoney?: Money;
    defaultValueOid?: string;
    defaultValueParameterDefinition?: ParameterDefinition;
    defaultValuePeriod?: Period;
    defaultValuePositiveInt?: number;
    defaultValueQuantity?: Quantity;
    defaultValueRange?: Range;
    defaultValueRatio?: Ratio;
    defaultValueReference?: Reference;
    defaultValueRelatedArtifact?: RelatedArtifact;
    defaultValueSampledData?: SampledData;
    defaultValueSignature?: Signature;
    defaultValueString?: string;
    defaultValueTime?: string;
    defaultValueTiming?: Timing;
    defaultValueTriggerDefinition?: TriggerDefinition;
    defaultValueUnsignedInt?: number;
    defaultValueUri?: string;
    defaultValueUrl?: string;
    defaultValueUsageContext?: UsageContext;
    defaultValueUuid?: string;
    element?: string;
    listMode?: 'first' | 'not_first' | 'last' | 'not_last' | 'only_one';
    logMessage?: string;
    max?: string;
    min?: number;
    type?: string;
    variable?: string;
}

export interface StructureMapGroupRuleTarget extends BackboneElement {
    context?: string;
    contextType?: 'type' | 'variable';
    element?: string;
    listMode?: 'first' | 'share' | 'last' | 'collate'[];
    listRuleId?: string;
    parameter?: StructureMapGroupRuleTargetParameter[];
    transform?: 'create' | 'copy' | 'truncate' | 'escape' | 'cast' | 'append' | 'translate' | 'reference' | 'dateOp' | 'uuid' | 'pointer' | 'evaluate' | 'cc' | 'c' | 'qty' | 'id' | 'cp';
    variable?: string;
}

export interface StructureMapGroupRuleTargetParameter extends BackboneElement {
    valueBoolean?: boolean;
    valueDecimal?: number;
    valueId?: string;
    valueInteger?: number;
    valueString?: string;
}

export interface StructureMapStructure extends BackboneElement {
    alias?: string;
    documentation?: string;
    mode: 'source' | 'queried' | 'target' | 'produced';
    url: string;
}

export interface StructureMap extends DomainResource {
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    experimental?: boolean;
    _experimental?: Element;
    group: StructureMapGroup[];
    identifier?: Identifier[];
    import?: string[];
    _import?: Element;
    jurisdiction?: CodeableConcept[];
    name: string;
    _name?: Element;
    publisher?: string;
    _publisher?: Element;
    purpose?: string;
    _purpose?: Element;
    status: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    structure?: StructureMapStructure[];
    title?: string;
    _title?: Element;
    url: string;
    _url?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}

