// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from './Attachment';
import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';


export interface SubstanceProteinSubunit extends BackboneElement {
    cTerminalModification?: string;
    cTerminalModificationId?: Identifier;
    length?: number;
    nTerminalModification?: string;
    nTerminalModificationId?: Identifier;
    sequence?: string;
    sequenceAttachment?: Attachment;
    subunit?: number;
}

export interface SubstanceProtein extends DomainResource {
    disulfideLinkage?: string[];
    _disulfideLinkage?: Element;
    numberOfSubunits?: number;
    _numberOfSubunits?: Element;
    sequenceType?: CodeableConcept;
    subunit?: SubstanceProteinSubunit[];
}

