// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Quantity } from './Quantity';
import type { Ratio } from './Ratio';
import type { Reference } from './Reference';


export interface SubstanceIngredient extends BackboneElement {
    quantity?: Ratio;
    substanceCodeableConcept?: CodeableConcept;
    substanceReference?: Reference<'Substance'>;
}

export interface SubstanceInstance extends BackboneElement {
    expiry?: string;
    identifier?: Identifier;
    quantity?: Quantity;
}

export interface Substance extends DomainResource {
    category?: CodeableConcept[];
    code: CodeableConcept;
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    ingredient?: SubstanceIngredient[];
    instance?: SubstanceInstance[];
    status?: 'active' | 'inactive' | 'entered-in-error';
    _status?: Element;
}

