// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { Quantity } from './Quantity';
import type { Range } from './Range';


export interface SubstanceAmountReferenceRange extends BackboneElement {
    highLimit?: Quantity;
    lowLimit?: Quantity;
}

export interface SubstanceAmount extends BackboneElement {
    amountQuantity?: Quantity;
    amountRange?: Range;
    amountString?: string;
    _amountString?: Element;
    amountText?: string;
    _amountText?: Element;
    amountType?: CodeableConcept;
    referenceRange?: SubstanceAmountReferenceRange;
}

