// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { DomainResource } from './DomainResource';
import type { Identifier } from './Identifier';
import type { Period } from './Period';
import type { Quantity } from './Quantity';
import type { Range } from './Range';
import type { Reference } from './Reference';
import type { Timing } from './Timing';


export interface SupplyRequestParameter extends BackboneElement {
    code?: CodeableConcept;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueRange?: Range;
}

export interface SupplyRequest extends DomainResource {
    authoredOn?: string;
    _authoredOn?: Element;
    category?: CodeableConcept;
    deliverFrom?: Reference<'Location' | 'Organization'>;
    deliverTo?: Reference<'Location' | 'Organization' | 'Patient'>;
    identifier?: Identifier[];
    itemCodeableConcept?: CodeableConcept;
    itemReference?: Reference<'Device' | 'Medication' | 'Substance'>;
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    occurrenceTiming?: Timing;
    parameter?: SupplyRequestParameter[];
    priority?: 'routine' | 'urgent' | 'asap' | 'stat';
    _priority?: Element;
    quantity: Quantity;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<'Condition' | 'DiagnosticReport' | 'DocumentReference' | 'Observation'>[];
    requester?: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
    status?: 'draft' | 'active' | 'suspended' | 'cancelled' | 'completed' | 'entered-in-error' | 'unknown';
    _status?: Element;
    supplier?: Reference<'HealthcareService' | 'Organization'>[];
}

