// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from './BackboneElement';
import type { CodeableConcept } from './CodeableConcept';
import type { ContactDetail } from './ContactDetail';
import type { DomainResource } from './DomainResource';
import type { UsageContext } from './UsageContext';


export interface TerminologyCapabilitiesClosure extends BackboneElement {
    translation?: boolean;
}

export interface TerminologyCapabilitiesCodeSystem extends BackboneElement {
    subsumption?: boolean;
    uri?: string;
    version?: TerminologyCapabilitiesCodeSystemVersion[];
}

export interface TerminologyCapabilitiesCodeSystemVersion extends BackboneElement {
    code?: string;
    compositional?: boolean;
    filter?: TerminologyCapabilitiesCodeSystemVersionFilter[];
    isDefault?: boolean;
    language?: string[];
    property?: string[];
}

export interface TerminologyCapabilitiesCodeSystemVersionFilter extends BackboneElement {
    code: string;
    op: string[];
}

export interface TerminologyCapabilitiesExpansion extends BackboneElement {
    hierarchical?: boolean;
    incomplete?: boolean;
    paging?: boolean;
    parameter?: TerminologyCapabilitiesExpansionParameter[];
    textFilter?: string;
}

export interface TerminologyCapabilitiesExpansionParameter extends BackboneElement {
    documentation?: string;
    name: string;
}

export interface TerminologyCapabilitiesImplementation extends BackboneElement {
    description: string;
    url?: string;
}

export interface TerminologyCapabilitiesSoftware extends BackboneElement {
    name: string;
    version?: string;
}

export interface TerminologyCapabilitiesTranslation extends BackboneElement {
    needsMap: boolean;
}

export interface TerminologyCapabilitiesValidateCode extends BackboneElement {
    translations: boolean;
}

export interface TerminologyCapabilities extends DomainResource {
    closure?: TerminologyCapabilitiesClosure;
    codeSearch?: 'explicit' | 'all';
    _codeSearch?: Element;
    codeSystem?: TerminologyCapabilitiesCodeSystem[];
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    expansion?: TerminologyCapabilitiesExpansion;
    experimental?: boolean;
    _experimental?: Element;
    implementation?: TerminologyCapabilitiesImplementation;
    jurisdiction?: CodeableConcept[];
    kind: 'instance' | 'capability' | 'requirements';
    _kind?: Element;
    lockedDate?: boolean;
    _lockedDate?: Element;
    name?: string;
    _name?: Element;
    publisher?: string;
    _publisher?: Element;
    purpose?: string;
    _purpose?: Element;
    software?: TerminologyCapabilitiesSoftware;
    status: 'draft' | 'active' | 'retired' | 'unknown';
    _status?: Element;
    title?: string;
    _title?: Element;
    translation?: TerminologyCapabilitiesTranslation;
    url?: string;
    _url?: Element;
    useContext?: UsageContext[];
    validateCode?: TerminologyCapabilitiesValidateCode;
    version?: string;
    _version?: Element;
}

