// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { DataRequirement } from './DataRequirement';
import type { Element } from './Element';
import type { Expression } from './Expression';
import type { Reference } from './Reference';
import type { Timing } from './Timing';

export interface TriggerDefinition extends Element {
    condition?: Expression;
    data?: DataRequirement[];
    name?: string;
    _name?: Element;
    timingDate?: string;
    _timingDate?: Element;
    timingDateTime?: string;
    _timingDateTime?: Element;
    timingReference?: Reference<'Schedule'>;
    timingTiming?: Timing;
    type: 'named-event' | 'periodic' | 'data-changed' | 'data-accessed' | 'data-access-ended' | 'data-added' | 'data-modified' | 'data-removed';
    _type?: Element;
}

