// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from './CodeableConcept';
import type { Coding } from './Coding';
import type { Element } from './Element';
import type { Quantity } from './Quantity';
import type { Range } from './Range';
import type { Reference } from './Reference';

export interface UsageContext extends Element {
    code: Coding;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueRange?: Range;
    valueReference?: Reference<'Group' | 'HealthcareService' | 'InsurancePlan' | 'Location' | 'Organization' | 'PlanDefinition' | 'ResearchStudy'>;
}

